# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 13:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to=b'')),
                ('date_upload', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignmentype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('nb_graders', models.IntegerField(default=3)),
                ('file_type', models.CharField(default=b'ipynb', max_length=20)),
                ('deadline_submission', models.DateTimeField()),
                ('deadline_grading', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Evalassignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_assignment', models.FloatField(blank=True, null=True)),
                ('grade_evaluation', models.FloatField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradapp.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='evalassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradapp.Student'),
        ),
        migrations.AddField(
            model_name='assignmentype',
            name='list_student',
            field=models.ManyToManyField(through='gradapp.Assignment', to='gradapp.Student'),
        ),
        migrations.AddField(
            model_name='assignmentype',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradapp.Prof'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignmentype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradapp.Assignmentype'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradapp.Student'),
        ),
    ]
