# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evalassignment',
            old_name='student',
            new_name='evaluator',
        ),
    ]
