# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0002_auto_20160920_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentype',
            name='title',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
