# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0003_assignmentype_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentype',
            name='list_student',
        ),
        migrations.AddField(
            model_name='assignmentype',
            name='list_students',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='assignmentype',
            name='file_type',
            field=models.CharField(default='ipynb', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignmentype',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
