# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0004_auto_20160921_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentype',
            name='list_students',
            field=models.FileField(blank=True, help_text='csv file, each row containsfirst_name, last_name, email', null=True, upload_to=''),
        ),
    ]
