# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0005_auto_20160921_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentype',
            name='deadline_grading',
            field=models.DateTimeField(help_text='DD/MM/YY'),
        ),
        migrations.AlterField(
            model_name='assignmentype',
            name='deadline_submission',
            field=models.DateTimeField(help_text='DD/MM/YY'),
        ),
    ]
