# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0006_auto_20160921_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentype',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
