# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0007_assignmentype_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalassignment',
            name='grade_assignment_comments',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='evalassignment',
            name='grade_evaluation_comments',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
