# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0008_auto_20160926_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentype',
            old_name='nb_graders',
            new_name='nb_grading',
        ),
    ]
