# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0009_auto_20160926_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalassignment',
            name='grade_assignment',
            field=models.FloatField(blank=True, help_text='/10', null=True),
        ),
        migrations.AlterField(
            model_name='evalassignment',
            name='grade_evaluation',
            field=models.FloatField(blank=True, help_text='/10', null=True),
        ),
    ]
