# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 11:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0011_auto_20160926_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalassignment',
            name='grade_evaluation',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(-1), django.core.validators.MinValueValidator(1)]),
        ),
    ]
