# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 11:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0013_auto_20160928_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalassignment',
            name='grade_assignment',
            field=models.FloatField(blank=True, help_text='/20', null=True, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)]),
        ),
    ]
