# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import gradapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0014_auto_20160929_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=gradapp.models.assignment_directory_path),
        ),
    ]
