# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 12:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0015_auto_20161002_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evalquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.IntegerField()),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('comments', models.TextField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='evalassignment',
            name='grade_evaluation',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AddField(
            model_name='evalquestion',
            name='evalassignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradapp.Evalassignment'),
        ),
    ]
