# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0016_auto_20161004_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentype',
            name='nb_questions',
            field=models.IntegerField(default=1),
        ),
    ]
