# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 13:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0017_assignmentype_nb_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentype',
            name='questions_coeff',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=1), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='assignmentype',
            name='list_students',
            field=models.FileField(blank=True, help_text='csv file, each row contains: first_name, last_name, email', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='evalassignment',
            name='grade_assignment_comments',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
