# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0018_auto_20161004_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentype',
            name='nb_grading',
            field=models.IntegerField(default=3, help_text='nb of files evaluated by each student'),
        ),
        migrations.AlterField(
            model_name='assignmentype',
            name='nb_questions',
            field=models.IntegerField(default=1, help_text='nb of questions in your assignment'),
        ),
    ]
