# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0019_auto_20161004_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentype',
            name='description',
            field=models.TextField(help_text='Use Markdown', max_length=500),
        ),
        migrations.AlterField(
            model_name='evalquestion',
            name='comments',
            field=models.TextField(blank=True, default='', help_text='Use Markdown', max_length=500),
        ),
    ]
