# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0020_auto_20161004_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalassignment',
            name='is_questions_graded',
            field=models.BooleanField(default=False),
        ),
    ]
