# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 13:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0022_auto_20161005_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalassignment',
            name='grade_evaluation',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
