# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 08:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gradapp', '0023_auto_20161107_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalassignment',
            name='evaluator_bis',
            field=models.ForeignKey(null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evalassignment',
            name='is_supereval',
            field=models.BooleanField(default=False),
        ),
    ]
