# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0025_auto_20161109_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evalassignment',
            name='evaluator',
        ),
        migrations.AlterField(
            model_name='evalassignment',
            name='evaluator_bis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
