# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0026_auto_20161109_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evalassignment',
            old_name='evaluator_bis',
            new_name='evaluator',
        ),
    ]
