# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0027_auto_20161109_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalquestion',
            name='comments',
            field=models.TextField(help_text='Use Markdown', max_length=500),
        ),
    ]
