# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-05 16:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradapp', '0029_assignmentype_questions_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentype',
            name='questions_statement',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=300), default=list, size=None),
        ),
    ]
